### ISSUE TITLE
Select startup folder functionality broken

### ISSUE THREAD

**Issue by RealTidBit5150** [protz/Manually-Sort-Folders#115] opened 2020-01-19 05:15 UTC
Appears to be same issue as #92. When selecting the inbox via "Extra Settings" regardless of the setting, TB always opens to the last selected folder.

**Comment by Well-Seasoned** [comment] 2020-01-27 16:00
I have the same issue.  Was fine until update to TB 64.8.1.  Regards.

**Comment by Webdongle** [comment] 2020-02-04 20:54
Looks like it has been fixed Version 2.0.2 4th Feb

**Comment by swbrains** [comment] 2020-06-26 14:22
Using TB 68.9 and v2.0.2 of this extension.  Couldn't get TB to use the specified startup folder as selected on the Extra Settings tab.  TB always starts using the last opened folder after selecting Local Folders->Inbox as the startup folder in the extension settings dialog.

**Comment by Webdongle** [comment] 2020-06-26 16:27
It did it a while ago and was fixed but now it's broke again

**Comment by Gluups** [comment] 2020-06-26 17:28
Oh, we have to remember that the extension was proposed to elderly people that were not interested in sorting the folders, but appreciated not to be disoriented by another starting folder after they clicked somewhere.
To say it more clearly, some people are interested only by the startup folder functionality, so let us try and get it work.

**Comment by protz** [comment] 2020-07-06 16:35
Duplicate of #92

**Closed by protz** 2020-07-06 16:35 UTC
Labels: bug
