### ISSUE TITLE
Update Thunderbird Version 115.3.1  has broken this great tool

### ISSUE THREAD

**Issue by ukmerlin** [protz/Manually-Sort-Folders#204] opened 2023-10-04 18:44 UTC
Would appreciate it if module was updated. Ta!

**Comment by potterpg** [comment] 2023-10-05 08:17
Yeah, Thunderbird auto updated, but as this is not working, I was sent hunting for the relevant folders in my email that are normally at the top, so for sure would like this working with the latest version if possible. Thanks for a great tool.

**Comment by meavethecat** [comment] 2023-10-05 10:45
Yes ! Please upgrade for Thunderbird 115.3.1 !!
I will contribute !

**Comment by VideoPod** [comment] 2023-10-05 15:37
Just sent an email to Johnathan about the Thunderbird 115.3.1 Update disabling his "Manually Sort Folders" Add-On.
I see he has over 160,000 Users so I'm sure others will be chiming in. I don't mind donating to his work if this can
be updated to work with Thunderbird 115.3.1, furthermore, if he's working on a new version I'd be interested in that
as well. Again, Let's Support this work.
Thank You. Murph

**Comment by itagagaki** [comment] 2023-10-05 22:34
Isn't this a DUPLICATE of #199?

**Comment by potterpg** [comment] 2023-10-09 09:08
> Isn't this a DUPLICATE of #199?

Indeed... thanks for highlighting it.

**Comment by changmw** [comment] 2023-10-10 14:07
Have been using this add-on for over a decade. 115.3.1 support would be great! I suspect it's not difficult to do so.

**Comment by itagagaki** [comment] 2023-10-10 22:58
Please continue at #199

**Closed as completed by itagagaki** 2023-10-10 22:58 UTC
