### ISSUE TITLE
Fields empty, non functional in TB60.0

### ISSUE THREAD

**Issue by lnz22** [protz/Manually-Sort-Folders#67] opened 2018-08-19 14:08 UTC
As you can see in following image, it’s empty.
I’m using TB 60.0 on the release channel
![image](https://user-images.githubusercontent.com/42516025/44309633-96463800-a3c1-11e8-85f2-55434af089d8.png)

**Comment by vcoeur61** [comment] 2018-08-21 08:41
Same issue with same TB Version (60.0)

**Comment by erwanlescop** [comment] 2018-08-24 02:01
Same issue since TB 60.0 (release), whilst it was still working correctly with TB 52.9.1 if I recall well.

Since it's look like this _extremely valuable extension_ is not maintained anymore: any idea of any decent **alternative add-on**?

**Comment by darkelfe14728** [comment] 2018-09-04 08:11
After testing, none buttons are functional, including the "close" (in TB 60.0)
And yes, work perfectly with TB 52.9

**Comment by hb9tst** [comment] 2018-09-04 16:07
Same problems after updating to TB 60.0. Basically, although the add-on is marked ok for TB 60, it does not work at all. Hope to get an update soon.

**Comment by grote** [comment] 2018-09-10 13:38
Looks like a duplicate of #60

**Comment by lnz22** [comment] 2018-09-10 20:06
Sent from a mobile device

________________________________

**Comment by nigelmay** [comment] 2018-09-14 19:18
I have the same issue- updated to 60.0 and this very useful add on is no longer functional.

**Comment by rfajman** [comment] 2018-09-18 06:52
I, too, have this problem.  I see that this extension hasn't been updated since 2016.  Is there any alternative (other than going back to an earlier version of Thunderbird)?

**Comment by wurmf** [comment] 2018-09-24 10:10
If anyone can fix this or if there is any alternative, please post it here!

**Comment by Keachie99** [comment] 2018-09-24 17:16
Same problem, gladly will send $20 to get this fixed.  I know you are busy, but 160000 folks depend on this.

**Comment by hb9tst** [comment] 2018-09-26 16:39
I think I managed to solve the TB60 issues, there are 20-30 lines of code to change, not more. Unfortunately, I just destroyed the XPI file and could not undelete it, so I'll have to redo the changes. I hope that I can put somewhere a patched XPI file tomorrow, waiting for the patched code to be pulled back.

**Comment by douglaswth** [comment] 2018-09-26 19:21
@hb9tst do you have a branch with your changes? That way you could make a pull request to this project.

**Comment by hb9tst** [comment] 2018-09-26 20:45
@douglaswth I don't have a branch yet: today I directly edited the original XPI in my TB extensions folder, then I had the great idea to uninstall the extension thus destroying the XPI (which was nowhere to be found among deleted files). I will branch the project tomorrow (and publish a temporary patched XPI for the time being) and remake the changes (it should take less than half an hour, now that I know what to correct), then I'll make the pull request.

**Comment by UtecRS** [comment] 2018-10-04 11:02
Are there any news on updates yet? 

@hb9tst were you able to solve the problem?

**Comment by hb9tst** [comment] 2018-10-04 14:34
The UI for folder sorting is still broken, however I managed to fix the tab to sort the accounts, where the problem was not related to RDF trees and thus easier to handle. For the time being, I inhibited the writing of the folder sort order to preferences, so those having an existing sort order created in a previous version of TB will not destroy them by just visiting the UI. Pushed changes to https://github.com/hb9tst/Manually-Sort-Folders, and the corresponding XPI is here: [MSF112b.zip](https://github.com/protz/Manually-Sort-Folders/files/2446738/MSF112b.zip)

**Comment by despecial** [comment] 2018-10-07 10:34
Here is another fork which adds the ability to sort the accounts.
Thanks to you both guys.

https://github.com/Ximi1970/Manually-Sort-Folders/releases

**Comment by frankx** [comment] 2018-10-08 05:15
Thanks. 

> The UI for folder sorting is still broken, however I managed to fix the tab to sort the accounts, where the problem was not related to RDF trees and thus easier to handle. For the time being, I inhibited the writing of the folder sort order to preferences, so those having an existing sort order created in a previous version of TB will not destroy them by just visiting the UI. Pushed changes to https://github.com/hb9tst/Manually-Sort-Folders, and the corresponding XPI is here: [MSF112b.zip](https://github.com/protz/Manually-Sort-Folders/files/2446738/MSF112b.zip)

works!

**Comment by UtecRS** [comment] 2018-10-08 06:32
> 
> 
> Here is another fork which adds the ability to sort the accounts.
> Thanks to you both guys.
> 
> https://github.com/Ximi1970/Manually-Sort-Folders/releases

works for me!

**Comment by UtecRS** [comment] 2018-10-08 06:33
> 
> 
> Here is another fork which adds the ability to sort the accounts.
> Thanks to you both guys.
> 
> https://github.com/Ximi1970/Manually-Sort-Folders/releases

works for me!

**Comment by githmw** [comment] 2018-10-08 17:16
> UtecRS said:
> Here is another fork which adds the ability to sort the accounts. Thanks to you both guys. https://github.com/Ximi1970/Manually-Sort-Folders/releases  works for me!

This fix works great in TBird 60.0 (32 bit), which I run on Windows 7 PRO (64 bit SP1). 

Thanks for the tip, and the author's hard work.

Harry

**Comment by jim-moe** [comment] 2018-10-08 19:17
TB 60.0 (64-bit)
tbsortfolders-1.2.0pre1.xpi performs as expected.
Thank you.

**Comment by grote** [comment] 2018-10-08 19:21
Can't @Ximi1970 do a proper pull request here, so @protz can release an **official** update that benefits *all* users?

**Comment by Ximi1970** [comment] 2018-10-08 19:26
Already done ;-)

**Comment by hb9tst** [comment] 2018-10-08 19:28
v1.2.0pre2 on https://github.com/Ximi1970/Manually-Sort-Folders/releases seems to work smoothly — well done and thanks for the nice work!

**Comment by protz** [comment] 2018-12-16 04:48
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as the new version is accepted. If you'd rather upgrade now:
- download the version "1.2.0pre3" listed in the comments above, or from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
- then, in Tools > Addons, hit the cog, the do "install addon from file".

Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan

**Closed by protz** 2018-12-16 04:48 UTC
