### ISSUE TITLE
Sort not working in compact view

### ISSUE THREAD

**Issue by Danno59** [protz/Manually-Sort-Folders#172] opened 2022-01-24 02:11 UTC
Hi
After manually sorting folders, they show up correctly except under compact view.
Can this be looked at.
TB version 91.5.0 (64-bit)

**Comment by itagagaki** [comment] 2022-01-24 02:51
Duplicate of #65 ?

**Comment by itagagaki** [comment] 2022-01-29 04:58
@Danno59 Don't you have any additional info?

**Comment by itagagaki** [comment] 2022-02-26 03:41
The issue is unclear, so close it.

**Closed by itagagaki** 2022-02-26 03:41 UTC
