### ISSUE TITLE
Patch Thunderbird and this addon to allow sorting all accounts (including RSS, Local Folders)

### ISSUE THREAD

**Issue by point-droid** [protz/Manually-Sort-Folders#101] opened 2019-10-14 13:29 UTC
I'm using the "Sort account" feature on Thunderbird 68.1.1 on openSuSE Leap 15.0. I am able to sort my email accounts in any order but when I apply changes the inbuilt "Local Folders" is always underneath all my other email accounts. I would like this at the top. Local Folders is not selectable as an account on the left hand side of the Sort account window but IS selected as the default account

Hope that makes sense and if you need any further info please ask

**Comment by seb303** [comment] 2019-10-18 09:38
I also have this same issue since TB 68.1.2 (on Windows 8.1)
It is no longer possible to make "Local Folders" appear at the top, even if it is selected as the default account.

**Comment by cyberbeat** [comment] 2019-10-19 09:25
I have the same problem, I would like to have local folders on top.

**Comment by Tinsus** [comment] 2019-10-22 19:10
Same problem for me: 68.1.2 (Win 10) MSF 2.0.2

**Comment by garvied** [comment] 2019-10-26 14:30
Same problem using thunderbird 68.1.2 on kubuntu 19.04 and MSF 2.0.2

**Comment by gabri25ele** [comment] 2019-11-06 10:06
version 2.0.2 doesn't let order local folders from the accounts. 
They rest undaunted on the bottom in the folder pane. 
Very annoying, when an update brings worsening instead of an improvement.

**Comment by adm-fkt-physik** [comment] 2019-11-06 12:09
Bug confirmed for
- Linux CentOS 7.7 (RHEL) 64-Bit, Thunderbird 68.2.0 64-Bit
- Windows 10 Education 1903 64-Bit, Thunderbird 68.2.1 64-Bit
Having "Local folders" on top is a must.

**Comment by nunoperalta** [comment] 2019-11-07 21:09
I'm looking for the same!
Really need the Local Folders on the top.

**Comment by Shitennouji** [comment] 2019-11-14 02:45
This function (the ability to pick Local Accounts as the default account to force) seems to be an uncontrollable case on the addon side.

The author (Manually sort folders by Jonathan Protzenko) clearly states on the ATN (addons.thunderbird.net) site.
https://addons.thunderbird.net/en-US/thunderbird/addon/manually-sort-folders/
Excerpt from “Version Information”:
Version 2.0.2 Released Sept. 26, 2019 74.6 KiB Works with Thunderbird 68.0 - *
This is an updated version for compatibility with Thunderbird 68. 
- The ability to pick Local Accounts as the default account to force it to appear first seems to have disappeared a couple Thunderbird releases ago.

In brief,
Because “API” of the function was deleted from Thunderbird 68.0 - * (the platform is Firefox ESR 68), 
“It is impossible unless the Thunderbird developer (Thunderbird Council) implement the API that supports it,” he expresses.
Thunderbird development team official support:
The Mozilla Thunderbird Blog | Thunderbird official blog
https://blog.thunderbird.net/
The Maildev Archives | Thunderbird's Issues and Progress: Monthly Archive
https://lists.thunderbird.net/pipermail/maildev_lists.thunderbird.net/
About "detailed roadmap for 2019":
[Maildev] thunderbird near term focus | 
https://lists.thunderbird.net/pipermail/maildev_lists.thunderbird.net/2018-October/001317.html

**Comment by seb303** [comment] 2019-11-14 10:46
Thanks Shitennouji for the info.

Do you have a link to where one can put a request to the Thunderbird devs for this API functionality to be added back?

**Comment by Shitennouji** [comment] 2019-11-14 14:25
Hi  seb303,
#1. Maildev Info Page | https://lists.thunderbird.net/
https://lists.thunderbird.net/mailman/listinfo/maildev_lists.thunderbird.net

#2. Forums — Mozilla | Contact Us : Forums & e-mail lists : Applications and Projects
https://www.mozilla.org/en-US/about/forums/
Applications and Projects
Please read the Mozilla forum etiquette document for posting rules and conventions.
 #  mozilla.dev.apps.thunderbird
     For development of Thunderbird, an email client built on the Mozilla platform.
        ● Mailing List: [dev-apps-thunderbird@lists.mozilla.org](https://lists.mozilla.org/listinfo/dev-apps-thunderbird)
        ● Newsgroup: mozilla.dev.apps.thunderbird
        ● Web: Google Groups

**Comment by seb303** [comment] 2019-11-14 16:14
Ok, thanks.  I did see those links in your original post, but the list info said that posting will be restricted to active Thunderbird developers.

I thought there might be something like bugzilla for Firefox where one can submit issues for the dev team to look at?  Looking now, there is a Thunderbird section on bugzilla which appears to be active.  I will give this a go...

**Comment by seb303** [comment] 2019-11-14 16:27
Referenced this add-on issue here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1583113

**Comment by protz** [comment] 2019-12-30 16:23
This (along with RSS sorting) requires deeper changes in Thunderbird which are being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1359410

**Comment by protz** [comment] 2020-07-06 16:26
Update: Thunderbird developers have committed to allowing sorting accounts (*not* folders) directly within Thunderbird, without the need for an addon. This will reuse some code that I (and others) wrote, which allows *arbitrary* reordering of accounts, meaning that this bug will be fixed automatically when the next version of Thunderbird comes out.

See https://bugzilla.mozilla.org/show_bug.cgi?id=244347 for a timeline and discussion.

**Closed by protz** 2020-07-06 16:26 UTC
Labels: bug

**Comment by gabri25ele** [comment] 2020-07-06 16:34
sorting accounts I hope in the panel folders (like local folder at the first place) otherwise, sorting accounts in settings is the most useless correctable functionality
