### ISSUE TITLE
Icons and arrows disappeared from the folder tree view since TB 102

### ISSUE THREAD

**Issue by Holmeow** [protz/Manually-Sort-Folders#189] opened 2022-08-17 11:52 UTC
I have a question and need your help
my thunderbird version is 102.1.2(64bit)

however，I can not manually sort ALL folders
because Tools - Manually Sort Folders can not display all folders
is this a bug?

shortcut as follows:
<img src = 'https://s3.bmp.ovh/imgs/2022/08/17/e4eec1308d11a003.jpg' />

need your reply ,thank you~

**Comment by itagagaki** [comment] 2022-08-21 08:17
Thanks for the captured image.
Please press Ctrl+Shift+J.
Error console will open.
Then please open Manually sort folders and select an account.
DEBUG messages are output every time you reselect an account.
Show it to us to the extent that you are willing to show it.

**Comment by itagagaki** [comment] 2022-08-21 09:40
After re-selecting the account or sorting method, you should have the following output. We need to know the lines after that.

> DEBUG	rebuild_tree(true);
> DEBUG	Sort method 2
>

**Comment by itagagaki** [comment] 2022-08-21 10:43
That's strange..
Here's a little something you might try.
If you have other add-ons that you use, try disabling them all and restart Thunderbird.
If the situation still does not change, try deleting them once rather than simply disable them.

**Comment by itagagaki** [comment] 2022-08-22 00:42
Try to double click "收件箱" or "test001" on Manually sort folder dialog.
The subfolders under them will be shown in tree structure.
However, those subfolders cannot be moved to deviate from the original tree structure. This is the current specification.

**Comment by itagagaki** [comment] 2022-08-22 02:03
You are right. That is not easy but I will try to find a solution.

**Comment by itagagaki** [comment] 2022-09-06 12:14
I reopen this issue now that the cause has been clarified.

In Thunderbird 91.13.0, the folder tree looked like below.

![collapsed](https://user-images.githubusercontent.com/71218184/188628734-f9073eae-f851-47b6-a72a-656465e9c6ad.png)
![expanded](https://user-images.githubusercontent.com/71218184/188628786-029ab01b-026b-4568-9061-8df392b64e20.png)

However, Thunderbird 102.0 shows it as below.

![TB102 0](https://user-images.githubusercontent.com/71218184/188630392-00351f1c-d36e-4ad7-98b0-e58c4b0683dd.png)

The icons are missing.

The arrows are also gone, so it is not possible to visually determine if there are any subfolders, but if you click where the arrow should be or double-click on the item, it will expand if there are any subfolders.

![TB102 0 expand](https://user-images.githubusercontent.com/71218184/188631149-74da425b-28c0-4985-b0ba-d8ddd97384e0.png)

I assume this is because Mozilla has already abandoned support for XUL and its code is not maintained, so it is gradually breaking down.

I'm considering workarounds.

**Comment by itagagaki** [comment] 2022-09-14 10:32
This issue has been fixed in version 2.2.2.

**Closed by itagagaki** 2022-09-14 10:32 UTC
