### ISSUE TITLE
Window is too small

### ISSUE THREAD

**Issue by robi400** [protz/Manually-Sort-Folders#107] opened 2019-11-26 12:16 UTC
Hy there, i use MSF a long time
in the latest version it is not possible to change the window size.
i have more than 6 Level in my MailAccount inside Thunderbird.
So please, if possible, make the Window much bigger or alow teh usere to resize it.
Thank in advance
RJ400

**Comment by protz** [comment] 2020-07-06 16:28
Duplicate of #116

**Closed by protz** 2020-07-06 16:28 UTC
Labels: feature-request
