### ISSUE TITLE
MSF not working

### ISSUE THREAD

**Issue by 47Dgo** [protz/Manually-Sort-Folders#160] opened 2021-08-16 14:57 UTC
Hello. I just installed this for Thunderbird 91 on Windows 10. but when clicking 'Manually sort folders' in the Tools menu, I get a window without any accounts or folders to select.  Others have also reported the same problem.

**Comment by skjerns** [comment] 2021-08-17 18:42
Is there a reason to use 91, and not the most recent stable version 78.13.0?

**Comment by itagagaki** [comment] 2021-08-21 06:20
duplicate of issue #159

**Closed by itagagaki** 2021-08-21 06:20 UTC
