### ISSUE TITLE
Account List not showing

### ISSUE THREAD

**Issue by TGWS2016** [protz/Manually-Sort-Folders#143] opened 2021-03-03 09:27 UTC
I'm getting the account list not showing bug.
Thunderbird 78.8.0
Extensions:
Manually sort folder 2.06
also Owl for Exchange 0.7.7.5
also provider for Google Calendar 78.0.1

**Comment by itagagaki** [comment] 2021-03-03 10:49
Thanks for the report.
We'll have to investigate..
If it's possible and it's not too much trouble, let me know what's in the debug console at startup and I might be able to give you a clue.
The console can be viewed by pressing Shift+Ctrl+I.

**Comment by KXKVI** [comment] 2021-03-23 01:03
TB 68.12.1 and MSF 2.06 here.  Not showing any accounts on the MSF UI if I have 4 e-mail accounts set up in TB.  However, if I add  a 5th e-mail account, the list populates and I can sort the accounts in any order I like.  Same issue on 4 different PC's. (Win 10 x64)

**Comment by itagagaki** [comment] 2021-03-23 09:27
@KXKVI Thanks for the report.
It would be great if you could share the contents of the debug console with us.
Of course, you are free to change the text to hide any privacy-related information.

**Comment by KXKVI** [comment] 2021-03-23 19:04
Glad to help.  Attached are two files containing output of the error logs.  I made one for the 4 e-mail account version (that doesn't work), and one for the 5 e-mail account version that does.  I didn't count "Local Folders" as an account.  I replaced all the personal information with asterisks (*).  I hope this is what you needed to help resolve the issue.  Let me know if I can assist further.

[Debug Log 4 Accounts.txt](https://github.com/protz/Manually-Sort-Folders/files/6192119/Debug.Log.4.Accounts.txt)
[Debug Log 5 Accounts.txt](https://github.com/protz/Manually-Sort-Folders/files/6192120/Debug.Log.5.Accounts.txt)

**Comment by itagagaki** [comment] 2021-04-04 10:27
@KXKVI Thanks for the error logs.
Can you try it out by installing the version I attached here?
Please rename this to tbsortfolders@xulforum.org.xpi and try to install it.

[tbsortfolders@xulforum.org.zip](https://github.com/protz/Manually-Sort-Folders/files/6254338/tbsortfolders%40xulforum.org.zip)

**Comment by KXKVI** [comment] 2021-04-04 17:28
Thanks for the updated file.  I installed it, and it is still working correctly.  I know that doesn't help you much, but since I added the 5th e-mail account, the add-on has been working fine.  I even tried dropping an account beforehand, but MSF still worked fine with the old file.  I guess all I can do going forward is to keep an eye on the issue and see if it reoccurs at some point with the new file.

Thanks again.

**Comment by itagagaki** [comment] 2021-04-05 00:50
Thanks for the report. Your error log helped me to understand why it was not working. It seemed that it was probably due to an anomaly in your TB preference file, not a bug in MSF. However, I took measures to make it work in such a case anyway. Yes, let's see how it works for a while. I will close this issue.

**Closed by itagagaki** 2021-04-05 00:50 UTC
