### ISSUE TITLE
Manually sort folders does not work with only RSS folders 

### ISSUE THREAD

**Issue by analogueworld** [protz/Manually-Sort-Folders#138] opened 2021-01-08 13:45 UTC
TB version:  portable 68.10.0

Issue: Using the plugin in a portable installation that includes both emails and RSS feeds, the add-on works. Using the add-on in a portable installation that includes only RSS feeds and no emails, the add-on does not work.

Summary: I tried separating my RSS feeds to a second portable installation as they have become too many. However, the add-on does not work without the presence of at least one email account. Is this intentional? 

Thank you

**Comment by itagagaki** [comment] 2021-08-31 16:50
@analogueworld 

Sorry, I couldn't find the cause of the issue.
Don't you plan to update your Thunderbird to the latest version?
In Thunderbird 91, the account management has been greatly improved, so this issue may have been resolved. And you can now sort your accounts in the Account Settings UI.
Thus, you no longer need to use this add-on to sort your accounts, but you can continue to use it to sort your folders, etc.
This add-on has also been updated to version 2.1.0, so please update it if you like and let me know the result.
Because I want to close this issue.

Manually sort folders version 2.1.0 is available on [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/)

**Comment by itagagaki** [comment] 2022-02-26 03:55
We have not received any reports that this issue has been resolved. But I consider this is obsolete. So I will close this.

**Closed by itagagaki** 2022-02-26 03:55 UTC
Labels: confirming
