### ISSUE TITLE
This add-on doesn't seem to add any features to Thunderbird 68.7.0 (64-bit)

### ISSUE THREAD

**Issue by quiversky** [protz/Manually-Sort-Folders#119] opened 2020-05-14 07:29 UTC
Either I am not able to understand the instructions or this plugin is not compatible with the latest version of Thunderbird with Lightning. 

There are no new tabs. There are no new options under "Tools".  The accounts and individual folders don't drag.

The only way I can reorder my accounts is to delete them all and add them back again in order.

**Comment by Gluups** [comment] 2020-05-14 08:17
Hello,
In case it helps, I am going to tell you what I obtain on my machine, and perhaps you will find what you mean at the end of the second tab. First thing to say, there is no support of drag and drop, do not loose time with that.
Windows 10 64 bits 1809 version 10.0.17763.1158.
Thunderbird 68.8.0 (64 bits).
Manually Sort Folders version 2.0.2 updated 26th Feb. 2020 (by the way, to know the version I had to go to Tools, complementary modules).
In the Tools menu, I have "Manually Sort Folders", displayed in French as my system is french.
When I click on that I obtain a dialog box with three tabs : Sort Accounts, Sort Folders, Advanced.
***
In the Sort Accounts tab, there are two lists on the left, one above "Local Folders", and one underneath. You cannot move an account from one to the other.
On the right, you have two buttons with arrows, up, and down. After you selected an account on the left, the arrows allow you to get it one step above or one step below (until the limits naturally).
Below "Local Folders", only one account (of newsgroups) is visible, but if there are more you can access to the others by drag and drop (the exception to what I said about no support of drag and drop).
***
In the Sort Folders tab, you have two dropdown lists on top, and a classical list on the left. 
The first dropdown list allows you to select an account, after what the classical list will display its folders. The second dropdown list proposes three methods of sorting. Oh, I guess buttons with arrows miss on this tab to allow to sort the folders, perhaps this is what you meant.
***
The advanced tab allows to select what folder will be displayed when opening Thunderbird, or if you want to display the last opened one.
+++
The menu button with three strokes displays a "complementary modules" entry, this gives a list of modules as you would guess, clicking on "Manually Sort Folders" gives you access to options for the extension. At a moment we talked about giving access to the dialog box from the menu button with three strokes, I am not sure this has been done.

**Comment by Gluups** [comment] 2020-05-14 08:29
Sorry I mixed up : the three strokes menu button gives access to a list of extensions, but it seems Manually Sort Folders is not in it.

**Comment by navennn** [comment] 2020-05-28 10:05
https://github.com/protz/Manually-Sort-Folders/issues/117

**Comment by schneeschmelze** [comment] 2020-06-05 23:58
The add-on works in TB 68.9.0 on macOS 10.13.6.

**Comment by Gluups** [comment] 2020-06-06 09:11
It would be a good thing that Quiversky describes his problem more accurately.

**Comment by jtagcat** [comment] 2020-06-06 15:14
> It would be a good thing that Quiversky describes his problem more accurately.

It is accurately described. It works on mac, bc mac shows the alt bar always.

**Comment by quiversky** [comment] 2020-06-07 02:38
I'm running Thunderbird 68.8.0 in Ubuntu 20.04.  This reorder plug-in used to work for me years ago but since I recently installed it, I don't see any new controls or way to reorder.

**Comment by Gluups** [comment] 2020-06-07 12:06
So, you mean no menu shows any presence of Manually Sort Folders, either drop-down or three-lined ?
Yesterday night on Windows I was updated to Thunderbird 68.9.0, perhaps the same is available for you too ? I doubt this is the point, but let us be precise.

**Comment by navennn** [comment] 2020-06-07 12:09
Guys, I linked another issue to this one, 10 days ago. It has the answer you're looking for.

**Comment by Gluups** [comment] 2020-06-07 12:19
> 
> 
> Guys, I linked another issue to this one, 10 days ago. It has the answer you're looking for.

I remember I read that, despite the extreme concision of your intervention here. 
You posted pictures to show the extension is in one menu, not the other. I asked the question about this to Quiversky.
I am afraid that subject 117 finishes with this :
"The addon definitely does not show in the Tools menu in TB77, either the hamburger menu or the top bar." (Rodalpho, 10 days ago).
Or are there several pages to read, that I should have forgotten to find ?

**Comment by quiversky** [comment] 2020-06-07 23:36
I've upgraded to the latest version available from Mozilla Thunderbird: 68.9.0.  There is still no option available. I believe the organisation of the menus is a bit different in the Linux version than MacOS or Windows.  There is no menu bar at the top of the application. There is a hamburger menu at the top between the main panel and the tasks panel on the right.   

![2020-06-08 09 33 47](https://user-images.githubusercontent.com/23070999/83982622-7c496100-a96b-11ea-8106-63eb8cbe364d.jpg)
![2020-06-08 09 33 56](https://user-images.githubusercontent.com/23070999/83982627-81a6ab80-a96b-11ea-8705-ffc4ec6209c9.jpg)

**Comment by Gluups** [comment] 2020-06-07 23:53
Thank you for having given more precision.
On my side I have got to wait somewhat before perhaps doing tests on Unix.
On Windows (that I more practice), applications also have a tendency to appear with no drop-down menus. But they exist, and you can have them appear with the alt key (press and release), or sometimes F10. Please try that to see whether something happens. And as I remember, in Unix you search Edit / Preferences, rather than Tools / Options.

When the programmers have time they will search again how to put the extension in the Hamburger menu, but the question has already been raised, and it does not seem that simple.

**Comment by gitwired649** [comment] 2020-06-08 07:09
> 
> 
> I've upgraded to the latest version available from Mozilla Thunderbird: 68.9.0. There is still no option available. I believe the organisation of the menus is a bit different in the Linux version than MacOS or Windows. There is no menu bar at the top of the application. There is a hamburger menu at the top between the main panel and the tasks panel on the right. I actually, couldn't screen-capture this directly as the hamburger menu closes when I tap PrtSc so I took it with my phone.
> 
> ![2020-06-08 09 33 47](https://user-images.githubusercontent.com/23070999/83982622-7c496100-a96b-11ea-8106-63eb8cbe364d.jpg)
Hi, i think this might help:

Quote #117 @navennn : "You must enable the topbar menu in thunderbird and access the tools from there."

Actually I got the same first reaction as @quiversky , and the found the answer in #117 .

> ![2020-06-08 09 33 56](https://user-images.githubusercontent.com/23070999/83982627-81a6ab80-a96b-11ea-8705-ffc4ec6209c9.jpg)

**Comment by Gluups** [comment] 2020-06-08 08:01
Well, please read : I said just that 7 hours sooner.
Once I obtain the answer that it works then we can speak about the personalization so that the menus are always visible. But I am pretty sure it is clearer to do it in those two steps, as it is far quicker to just have to depress the Alt key.

**Comment by rodalpho** [comment] 2020-06-08 20:17
Again, in Thunderbird beta version 77 this extension _does not show in the top menubar._ It is completely nonfunctional.

**Comment by schneeschmelze** [comment] 2020-06-08 22:08
For what it's worth, it's right, the package's menu does not appear in the hamburger menu on macOS, either. So, we probably have to get used to the idea that  we will lose this add-on later this year if we keep updating Thunderbird.

**Comment by schneeschmelze** [comment] 2020-06-08 22:14
![Ohne Titel](https://user-images.githubusercontent.com/20168163/84085468-f1f21300-a9e5-11ea-8f8e-2dc0e05cf2ff.png)
This is how the tools submenu in the hamburger menu looks on the Mac.

**Comment by Gluups** [comment] 2020-06-08 22:15
> Again, in Thunderbird beta version 77 this extension _does not show in the top menubar._ It is completely nonfunctional.

Hello, you said this in two threads dedicated to version 68, as appears in the title.
I do not master very well what must be done about beta versions, but another thread would be welcome, so I presume you should click on the "New issue" button on top of the page, even if after that your post will be copied to the same mailboxes.
I ignore the current reactivity of the volunteer developers (one who created the extension, and a few ones who helped in an emergency context when he could spend no time on this) but at least the attention of people reading the thread will be focused on your version, and in the list of issues it will appear that one addresses version 77.

**Comment by Gluups** [comment] 2020-06-08 22:37
> 
> 
> For what it's worth, it's right, the package's menu does not appear in the hamburger menu on macOS, either. So, we probably have to get used to the idea that we will lose this add-on later this year if we keep updating Thunderbird.

Hello, I am afraid the support for the Hamburger menu has not yet been developed at all. I remember I saw that was noticed a moment ago, so it has been seen, I presume we have to wait for a developer to learn how to do that. Please remember that the extension is proposed by developers on their free time.
In this thread opened by Quiversky I try and guide him in using the drop-down menu, supposing it works on his version.
In the meanwhile, other posts appeared :
* to insist that the Hamburger menu does not show Manually Sort Folders
* to claim that the extension does not work on version 77 of Thunderbird, either with the Hamburger menu or the drop-down menu anyway.

**Comment by AlbertJP** [comment] 2020-07-02 10:31
In Thunderbird 68.8.0 on Linux it does not work either - nothing in the hamburger menu, and the addon itself has no 'options' button in the addon list anymore.

**Comment by protz** [comment] 2020-07-06 16:25
Duplicate of #117

**Closed by protz** 2020-07-06 16:25 UTC
