### ISSUE TITLE
Not working in TB 78.0

### ISSUE THREAD

**Issue by DavidBE-UK** [protz/Manually-Sort-Folders#123] opened 2020-07-16 22:33 UTC
I  updated TB today from 68.10 to the new 78.0. Sadly this extension is not working - no entry in any tools menu. I note that the order of accounts I had set with the add-on before has persisted, but the Local Folders have reverted to alphabetical from how I had them.

**Comment by Gluups** [comment] 2020-07-16 22:51
Hello,
So I imagine you mean you do not see Manually Sort Folders, neither in the drop-down menu, nor in the Hamburger menu -for version 78 (on what platform is this ? Is it a beta version ?)
Concerning the position of Local Folders, I have no in-depth knowledge of the problem, but it has been said several times that some versions of Thunderbird do not allow any more to position the local folders on demand, so I am afraid it will not be possible to give you satisfaction on this point, until Thunderbird evolves this way.

**Comment by DavidBE-UK** [comment] 2020-07-16 22:58
Windows 10 2004 64-bit laptop. TB is 78.0 NOT beta - it was released today (but like with 68.0 it's not showing up in TB itself as an update, you have to download the TB 78.0 installer from the main TB website page).

The local folders were in the order I'd put them still with 68.10 today before the update to 78.0. They're the only thing that's changed after the update. I can't test if the extension would re-order them again as I don't see Manually Sort Folders in either the Tools drop-down menu or hamburger menu.

**Comment by DavidBE-UK** [comment] 2020-07-16 23:06
Oh, my wanted local folder order is still in about:config under extensions.tbsortfolders@xulforum.org.tbsf_data

**Comment by ztNFny** [comment] 2020-08-04 16:46
not showing in Tools menu is #117 
But in addition to not showing up it's also not sorting in TB78, so I suggest to use this Issue to track this and change title to "Folder sorting broken in TB78"

**Comment by devrimsen** [comment] 2020-08-16 19:49
The addon is not working in TB78.1.1 due to "Manually sort folders is incompatible with Thunderbird 78.1.1". Will this issue be fixed, if yes when?

**Comment by wsmwk** [comment] 2020-08-19 00:06
pretty much duplicate of issue #102

**Closed by wsmwk** 2020-08-19 00:06 UTC
