### ISSUE TITLE
Tbird 68.3.1 update broke it

### ISSUE THREAD

**Issue by GetIT-GotIT-Good** [protz/Manually-Sort-Folders#109] opened 2020-01-05 00:20 UTC
Windows 10 Pro

Folder listing populates new window, but no controls appear, thus no functionality.

**Comment by ondrasvoboda** [comment] 2020-01-09 11:54
Also moving local folders on top using default account option is not working in this version.

**Comment by elgonzo** [comment] 2020-02-12 12:48
Duplicate of https://github.com/protz/Manually-Sort-Folders/issues/101

**Comment by protz** [comment] 2020-07-06 16:27
Duplicate of #112 -- can you comment there if you're still experiencing the issue?

**Closed by protz** 2020-07-06 16:27 UTC
