### ISSUE TITLE
Setting Local Folders as default account doesn't make it appear at the top

### ISSUE THREAD

**Issue by libcub** [protz/Manually-Sort-Folders#155] opened 2021-06-05 08:57 UTC
I set Local Folders as the default account on the Sort Accounts tab, and restarted Thunderbird. Local Folders is shown as the default account on the right side of the Sort Accounts tab, but it not displayed as the first account in the account pane of TB.

TB 78.11.0, Windows 10

**Comment by seb303** [comment] 2021-08-01 05:03
I too would like to see this fixed.

Sorting Local Folders above the mail accounts has been broken for a long time now.  I believe it broke due to a change in the core Thunderbird, and there has been lengthy (& slow) discussion within the Thunderbird dev team on the best solution to bring back this functionality.  I can't find the bugzilla link now to check on the progress unfortunately.

**Comment by seb303** [comment] 2021-08-01 05:47
Found the bugzilla links...
https://bugzilla.mozilla.org/show_bug.cgi?id=1359410
https://bugzilla.mozilla.org/show_bug.cgi?id=1583113
https://bugzilla.mozilla.org/show_bug.cgi?id=1606664

But also found [this closed issue](https://github.com/protz/Manually-Sort-Folders/issues/101) which states that sorting accounts will be available in the core Thunderbird, and won't ever be fixed in this addon.  The issue refers to [this discussion on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=244347). Current status is Closed / RESOLVED FIXED so I guess it's working already.

I believe it will be available in TB version 89, which is available now via TB beta channel, and I guess around November 2021 via the TB release channel, assuming this continues to follow the [Firefox ESR schedule](https://wiki.mozilla.org/Release_Management/Calendar).

**Comment by JoanEliot** [comment] 2021-08-09 21:48
Does anyone know why the option is present in the 'Sort accounts' tab, if it doesn't work and isn't expected to?

**Comment by itagagaki** [comment] 2021-08-11 01:46
I don't know, maybe it used to work but stopped working after a certain version of TB and now we are waiting for TB to return to its original state?

**Comment by itagagaki** [comment] 2021-08-31 17:04
@libcub @seb303 Currently, the latest version of Thunderbird is 91.0.3, and this add-on has been updated to version 2.1.0. Can you please update and try?

**Comment by seb303** [comment] 2021-10-04 09:53
Confirmed working in TB 91.1.2 both via the Manually sort folders UI and the TB Account Settings UI.

**Comment by itagagaki** [comment] 2021-10-04 11:27
@seb303 Thanks for reporting back!

**Closed by itagagaki** 2021-10-04 11:27 UTC
Labels: confirming
