### ISSUE TITLE
How to let me define for certain sub folders an alphabetical sort order (and for all other a manual)?

### ISSUE THREAD

**Issue by pstein** [protz/Manually-Sort-Folders#182] opened 2022-04-01 20:39 UTC
How can I tell MSF to apply an alphabetical sort order only for some sub folder.
For all other folders a manual sort order should be effective

How can I achieve this?

**Comment by itagagaki** [comment] 2022-04-05 12:31
duplicate of issue #14

**Closed by itagagaki** 2022-04-05 12:31 UTC
