### ISSUE TITLE
Local folder always the last. How to tweak them manually?

### ISSUE THREAD

**Issue by milanraf** [protz/Manually-Sort-Folders#135] opened 2020-11-04 09:49 UTC
Many thanks you for this truly useful addon!

Anyway, Local Foders are always at the end of the list.
Is there a way to put them on the top? Even a manually procedure would be really appreciated.

Thank you

Raf

**Comment by protz** [comment] 2020-11-04 15:49
Duplicate of #133

**Closed by protz** 2020-11-04 15:49 UTC
