### ISSUE TITLE
Plugin does not appear in the hamburger menu on Thunderbird 68 and later

### ISSUE THREAD

**Issue by sholl** [protz/Manually-Sort-Folders#117] opened 2020-02-03 11:11 UTC
Hi,

since the last (auto-) update of thunderbird the nice plugin is no longer compatible. Are there any plans to support this version of TB?
I am on Windows 10 64bit running TB 68.4.1. The plugin is not loaded from TB though.

TIA

    Stephan

**Comment by xsltmaster** [comment] 2020-02-11 01:49
You didn't specify the platform or symptom. I may have the same problem. Running TB 68.4.1 in the Linux VM on a Chromebook, the extension doesn't add its selection in the Tools menu.

**Comment by elgonzo** [comment] 2020-02-12 12:14
Running TB 68.4.2 here, and the plug-in loads just fine.

Note though that the plug-in functionality is kinda broken due to changes in the Thunderbird code base. The plug-in developer (protz) is in communication with the Thunderbird developers to sort out (pun intended) the problem.  See also issue https://github.com/protz/Manually-Sort-Folders/issues/101

**Comment by zampanoo** [comment] 2020-02-14 15:26
Same problem here (Linux Mint 19.3) with TB 68.4.1: no entry created under "tools", unfortunately.

Also, the link in the description of the extension produces a "malformed request" and hence does not reach this page.  

An update of this lovely & helpful extension would be much apprecitated, if possible. Thx.

**Comment by navennn** [comment] 2020-02-21 12:45
Same issue here, the menu entry does not appear in tools.
Thunderbird 68.4.1
Linux 4.15.0-88-generic
Plugin version 2.0.2

**Comment by Nemesis77swe** [comment] 2020-03-05 06:52
Confirmed by me too, but this issue has been open 1 month, nothing from the creator?

**Comment by zampanoo** [comment] 2020-03-05 09:46
> Confirmed by me too, but this issue has been open 1 month, nothing from the creator?

Hey Nemesis, this person offers something for free! I do not think that anything other than kindly asking for an update is appropriate...

**Comment by jtagcat** [comment] 2020-03-05 11:08
Please don't 'me too' comment on any forum or issue posts. That's what the +1 button is for. Just click the upvote button on the original post:
![image](https://user-images.githubusercontent.com/38327267/75975987-7017b880-5ed1-11ea-9f7b-4d8e148c3140.png)
and subscribe:
![image](https://user-images.githubusercontent.com/38327267/75975999-773ec680-5ed1-11ea-9138-b6c2aa7bc7e5.png)

That way you don't send out a notification out to me, anyone in this issue, or anyone else on the internet.
Pardon me sending out notifications, but this is the 3rd time I have received a notification due to someone commenting 'me too'.

**Comment by pstein** [comment] 2020-04-15 10:51
All users above talked about the bug in v68.4.1 and Linux

Is this bug eventually fixed in v68.4.2?

Is this a Linux-only bug?
What about Windows Version?

**Comment by rodalpho** [comment] 2020-05-27 18:41
This addon also doesn't work with Thunderbird 77.0b3, the latest beta release as I post this. It seems to load fine but nothing shows up in the Tools menu.

**Comment by tx350z** [comment] 2020-05-28 09:52
It works with 68.8.1 on Windows.

**Comment by navennn** [comment] 2020-05-28 10:04
Hi
I discovered that it is actually appearing in the menu for me.
Except, the 'tools' menu is different since TB 68.x. You must enable the topbar menu in thunderbird and access the tools from there. And it does work.

It's here
![Screenshot from 2020-05-28 12-00-30](https://user-images.githubusercontent.com/26810830/83128154-4be80400-a0db-11ea-8aa2-37e871d2f97d.png)

But not here

![Screenshot from 2020-05-28 12-00-51](https://user-images.githubusercontent.com/26810830/83128215-628e5b00-a0db-11ea-8355-6c1a8024956a.png)

**Comment by rodalpho** [comment] 2020-05-28 18:44
The addon definitely does not show in the Tools menu in TB77, either the hamburger menu or the top bar.

**Comment by rodalpho** [comment] 2020-06-22 21:27
Also broken in TB78 beta.

**Comment by wlsc** [comment] 2020-07-11 08:28
Doesn't work with 68.10.0 (64-bit) version.

**Comment by Gluups** [comment] 2020-07-11 09:12
> 
> 
> Doesn't work with 68.10.0 (64-bit) version.

Hello,
I just tested "Manually Sort Folders" with this version, on Windows 10 64 bits 1909, [version 10.0.18363.900].
The extension does not appear in the Hamburger menu, but this problem has been raised some months ago already -and right that it is the title of this thread.
I had UI problems with a 150% system zoom, as the buttons were hidden behind the task bar, so I had to move the dialog box upwards through its system menu actioned with the keyboard, and then as it comes back to its previous position, evaluate how many times I have to depress the tab key before pressing Enter, to action the first button of the dialog box.
The second tab, sort the folders, has no buttons, so I imagine we can do nothing with it. About this topic, I should like to signal that in the newsgroups you can sort them by drag and drop.
I saw no problem with the two other tabs, I could change the order of the accounts and choose a folder to be selected when opening Thunderbird.
So, I am afraid you would have to elaborate somewhat the problems you meet.

**Comment by protz** [comment] 2020-09-28 13:51
This is now fixed courtesy of @itagagaki -- the new version with the fix is 2.0.4 and should be approved shortly.

**Closed by protz** 2020-09-28 13:51 UTC

**Comment by pgnd** [comment] 2020-09-28 16:31
@protz 

with
```
    Name: Thunderbird
    Version: 68.12.0
    Build ID: 20200820223055

    Update Channel: release
    User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Thunderbird/68.12.0
    OS: Linux 5.8.11-200.fc32.x86_64

    Multiprocess Windows: 0/0
              Disabled
    Remote Processes: 0
    Enterprise Policies: Inactive
    Google Location Service Key: Missing
    Google Safebrowsing Key: Missing
    Mozilla Location Service Key: Missing
    Safe Mode: false
    ...
```

having just upgraded to 

```
...
        Manually sort folders
        2.0.4
        true
        tbsortfolders@xulforum.org
...
```

after restart, there's no trace of any option -- in menus/context/prefs ... anywhere, afaict -- to sort, or even access preferences

can verify it on 10+ boxes; admittedly, all same versions of TBird + MSF.

if there's additional detail you need, pls specify

**Comment by protz** [comment] 2020-09-28 16:46
<img width="288" alt="Screen Shot 2020-09-28 at 12 45 48 PM" src="https://user-images.githubusercontent.com/214707/94461770-6c9a9600-016f-11eb-8125-9ebfbd98bb9a.png">

here?

**Comment by protz** [comment] 2020-09-28 16:46
<img width="44" alt="Screen Shot 2020-09-28 at 12 46 26 PM" src="https://user-images.githubusercontent.com/214707/94461822-7c19df00-016f-11eb-9551-b1e8b0c211c8.png">

hamburger menu

**Comment by pgnd** [comment] 2020-09-28 17:00
@protz 

nope, nada:

![tools menu](https://i.imgur.com/Qk1ZM7V.png)

**Comment by protz** [comment] 2020-09-28 17:03
we are talking only about the hamburger menu; this is the menu bar and the addon no longer appears in there

**Comment by protz** [comment] 2020-09-28 17:03
but maybe for backwards-compat we should also aim for the legacy menu bar, since that's where the addon used to be found? pinging @itagagaki for thoughts :)

**Comment by pgnd** [comment] 2020-09-28 17:12
@protz 

I've long-ago removed the 'burger menu icon; not a fan, and usually incomplete.  but that's personal/company preference.

that said, replacing it, here's that^ view,

![burger tools](https://i.imgur.com/tD2QTTc.png)

**Comment by BillH99999** [comment] 2020-09-28 17:14
@protz 

I'm using TB 68.12.1 and TB 73.3.1.  On both of these it shows in the hamburger menu, but it also shows in the Tools menu in the menu bar.

![image1](https://user-images.githubusercontent.com/26846819/94464430-51318a00-0173-11eb-8f2b-8b4a9d40ef50.jpg)

**Comment by ztNFny** [comment] 2020-09-28 17:14
78.3.1 and 2.0.4, both menu + hamburger are ok for me

**Comment by schneeschmelze** [comment] 2020-09-28 17:20
Same here. The menu entry for MSF shows in both the Hamburger menu and the Tools menu in TB 78.3.1 on MacOS 10.13.6.

**Comment by pgnd** [comment] 2020-09-28 17:20
fwiw, just did a quick ping with a larger sample set of just-upgraded users ... 100% of ~35 users see the same issue -- no more trace of it.
all using 68.12.0 + v2.0.4 on linux.
so if it's pebkac, at least we're consistent!

**Comment by protz** [comment] 2020-09-28 17:21
ah indeed -- I had not noticed that this already worked with the latest update; @pgnd must have some other issue then; anything in tools > error console?

**Comment by protz** [comment] 2020-09-28 17:21
FWIW I'm on 68 and this works for me

**Comment by pgnd** [comment] 2020-09-28 17:29
@protz 

to be lear, *prior* to the v2.0.4 update, it was visible in menus.  *after* it's ... vanished.

turned on everything in conosle; not a single peep re: MSF; other usual info is there ...

it's acting as if it's not loading at all, let alone functions.  digging around more, atm ...

**Comment by itagagaki** [comment] 2020-09-28 23:27
68.12.0 + v2.0.4 on Windows is OK for me. But not tested on Linux. That's the only thing I'm concerned about at the moment.
I'm not sure that there's a difference between Linux and Windows...I'll look into it when I have time.
@pgnd You were able to use 2.0.2, weren't you? For now, I recommend you continue to use 2.0.2.
The main difference in 2.0.3 is that it now supports TB 78. The main difference in 2.0.4 is that it now supports the hamburger menu, which you don't like. Neither of these seems to matter much to you.

**Comment by pgnd** [comment] 2020-09-28 23:47
@itagagaki 

> You were able to use 2.0.2, weren't you? For now, I recommend you continue to use 2.0.2.

yep.  and, dropping BACK to v2.0.2 'cures' the problem:

 item available in Tools menu
 as expected, NOT available in Hamburger
 works as expected; folder sorts are doable & persistent across restarts

so the dial-back is certainly doable -- simply causes problems for those for whom the update was made available, and don't know to/how to downgrade.

**Comment by itagagaki** [comment] 2020-09-29 00:16
@pgnd 

How to downgrade to 2.0.2

Tools -> Add-ons
Click Manually sort folders
![image](https://user-images.githubusercontent.com/71218184/94497214-7ab0eb00-0231-11eb-910d-4cebf448bb9d.png)
![image](https://user-images.githubusercontent.com/71218184/94497331-d9766480-0231-11eb-8ba0-3c5710f7d405.png)
Scroll to bottom
![image](https://user-images.githubusercontent.com/71218184/94497245-987e5000-0231-11eb-8a80-aa6e20148e76.png)
Turn "Automatic Updates" Off
![image](https://user-images.githubusercontent.com/71218184/94497432-235f4a80-0232-11eb-9cd7-c6b14791b94a.png)
Type "Manually sort folders" in "Find more extensions" box and hit ENTER key
![image](https://user-images.githubusercontent.com/71218184/94497643-c9ab5000-0232-11eb-8c92-f4061ea721e1.png)
Find "Manually sort folders" and click it (Do NOT click "Add to Thunderbird")
![image](https://user-images.githubusercontent.com/71218184/94497777-3f172080-0233-11eb-86a5-36151edc2dd5.png)
The Manually sort folders' page will be open
![image](https://user-images.githubusercontent.com/71218184/94497837-67068400-0233-11eb-8f67-dfbaae6649d9.png)
Scroll to bottom and click "Version Information"
![image](https://user-images.githubusercontent.com/71218184/94497901-987f4f80-0233-11eb-85ca-4fa0770dcd25.png)
Click "See complete version history"
![image](https://user-images.githubusercontent.com/71218184/94497948-c369a380-0233-11eb-8260-02c309403cf9.png)
Find Version 2.0.2 and click "Add to Thunderbird"
![image](https://user-images.githubusercontent.com/71218184/94498009-f14ee800-0233-11eb-8d07-fc53f330751a.png)
That's all :-)

**Comment by protz** [comment] 2020-09-29 01:22
ok, let's post here if someone can figure out why this is not working on linux -- I can mark 2.0.3 and 2.0.4 as not compatible with 68 in the meanwhile, how about that?

**Comment by pgnd** [comment] 2020-09-29 01:28
lol.  yes, *i* am aware of how to downgrade.  that^ is beyond my office users ;-)

in the meantime, a kludgy ansible scripts should do the trick!

in any case, this'll all work itself out if/when next update addresses a fix.

@protz that _would_ prevent users getting bitten, iiuc the way updates work.
but, i'm the only one in here (well, me & my users), having an issue ... could still be peblac.
so take it with grain of salt!  up to you ...

**Comment by ztNFny** [comment] 2020-09-29 05:25
@protz i'm on linux, 78.3.1 with 2.0.4 and have both entries. So not a linux problem.

**Comment by lgbaldoni** [comment] 2020-09-29 06:13
> ok, let's post here if someone can figure out why this is not working on linux -- I can mark 2.0.3 and 2.0.4 as not compatible with 68 in the meanwhile, how about that?

If I understand correctly, the "hamburger menu" is the thing with the three horisontal bars?
If so, I can confirm the plugin settings don't appear there using 68.12.0 on linux.

**Comment by itagagaki** [comment] 2020-09-29 09:43
WSL2 + Ubuntu 20.04.1 LTS + Thunderbird 68.10.0 (64-bit) + MSF 2.0.4 works fine.
Both [Menubar>Tools] and [Hamburger>Tools] have "Manually sort folders" entry.

@pgnd I'm not sure why yours is not working properly. Try disabling all other add-ons to try it out if you have the time.

**Comment by mlipok** [comment] 2020-09-29 09:50
78.3.1 
Starts working today without any manual integration (I not install any update for this "Manually-Sort-Folders" addon).

**Comment by protz** [comment] 2020-09-29 13:34
Are people with the issue using a regular English release of Thunderbird?

**Comment by ztNFny** [comment] 2020-09-29 14:51
@protz en-US, linux tar.gz here, all goof. So thats mot it.

**Comment by pgnd** [comment] 2020-09-29 15:26
@itagagaki 

> I'm not sure why yours is not working properly. Try disabling all other add-ons to try it out if you have the time.

test:

Clean install of TBv68.12.0, new profile, one extension installed -- MSF v2.0.4

No trace of it.  Nothing in Hamburger menu, or Tools menu.

No errors, or related info in console. at all.

Drop back to 2.0.2, all's good, as reported above.

@protz 

> Are people with the issue using a regular English release of Thunderbird?

yep.

**Comment by itagagaki** [comment] 2020-09-29 17:04
@pgnd Thanks the test.

Hmm..

To get a clue, I installed TB68.12 on my Linux (Ubuntu 20.04.1 LTS on WSL2) and run it.

Download TB68.12.0 for linux-x86_64/en-US on my Ubuntu 20.04.1 LTS
http://ftp.mozilla.org/pub/thunderbird/releases/68.12.0/linux-x86_64/en-US/thunderbird-68.12.0.tar.bz2

Extract and run
![image](https://user-images.githubusercontent.com/71218184/94588097-71219480-02be-11eb-8793-113839aff1f0.png)

Install MSF v2.0.4 from Tools > Add-ons
![image](https://user-images.githubusercontent.com/71218184/94588478-e7be9200-02be-11eb-8a7d-ae71cd37bfbc.png)
![image](https://user-images.githubusercontent.com/71218184/94588170-8dbdcc80-02be-11eb-8871-217e84360eb7.png)

Manu Bar > Tools
![image](https://user-images.githubusercontent.com/71218184/94588584-0cb30500-02bf-11eb-9c0e-00e4a6c46b88.png)

Hamburger Button > Tools
![image](https://user-images.githubusercontent.com/71218184/94588772-54399100-02bf-11eb-8b70-e167ce9b08b1.png)

As you can see, it worked fine..

There doesn't seem to be any errors to worry about.
![image](https://user-images.githubusercontent.com/71218184/94589969-ed1cdc00-02c0-11eb-8f36-73fad98a422e.png)

**Comment by pgnd** [comment] 2020-09-29 17:36
@itagagaki 

my result is 100% consistent across all my test boxes.

it's _gotta_ be something unique/consistent in my environment*S*.

i'll be darned if i can find the silly problem.

yet ...

**Comment by itagagaki** [comment] 2020-10-03 00:44
@pgnd 
Are you still watching here?
I would like to know why the new version of MSF is not working well in your environment.
I'm sure 2.0.2 is good for you, but are you willing to help us find the cause?
You did clean install of TB68.12.0. Where did you actually get it from?
I got it from the following URL. Is it the same one?
I tried this but it was unable to reproduce the issue.
http://ftp.mozilla.org/pub/thunderbird/releases/68.12.0/linux-x86_64/en-US/thunderbird-68.12.0.tar.bz2

@lgbaldoni 
> If I understand correctly, the "hamburger menu" is the thing with the three horisontal bars?
> If so, I can confirm the plugin settings don't appear there using 68.12.0 on linux.

Yes. That's what we call a hamburger menu.
When you click on it, you will see 'Tools' in the menu that comes up.
If you click on it further, 'Manually sort folders' should appear. Doesn't it appear?

**Comment by pgnd** [comment] 2020-10-03 01:07
@itagagaki

> Are you still watching here?

yep o/

> I would like to know why the new version of MSF is not working well in your environment.
> I'm sure 2.0.2 is good for you, but are you willing to help us find the cause?

sure.  atm, I'm idling at 'WTF?".  

if _you_ know how to get relevant info out of TB etc, let me know ... & I'll provide.

i'd be happier if I could get a useful error out of this; I suspect I may have to go find/dust-off my TB-debug notes ... 

> You did clean install of TB68.12.0. Where did you actually get it from?

upstream,  from Moz. only.

i don't generally use distro releases.

> I got it from the following URL. Is it the same one?
> I tried this but it was unable to reproduce the issue.
> http://ftp.mozilla.org/pub/thunderbird/releases/68.12.0/linux-x86_64/en-US/thunderbird-68.12.0.tar.bz2

yep. for the clean installs.

i also started with a variety of earlier versions -- also always/only from upstream 00 that got upgraded through the built-in app upgrade mechanism.

same results in all cases.  here anyway.

**Comment by itagagaki** [comment] 2020-10-03 03:19
@pgnd 
1. Open Tools>Developer Tools>Error Console
2. Open Tools>Add-ons
3. Disable Manually sort folders
4. Enable Manually sort folders
5. See Error Console. It would be a clue if you get any errors or something.

Here's what mine looks like.
![image](https://user-images.githubusercontent.com/71218184/94982017-35aef080-0572-11eb-8877-e93a860f3d4a.png)

**Comment by pgnd** [comment] 2020-10-03 03:37
@itagagaki 

update TB, now @
```
Name 	Thunderbird
Version 	68.12.1
Build ID 	20200929010218
```

upgrade MSF,
```
Extensions
	Manually sort folders	2.0.4	true	tbsortfolders@xulforum.org
```

restart TB

enable tracing ALL options in console

manual DISABLE/ENABLE of MSF

there's one, and only one, message in console:
```
TypeError: messenger.WindowListener is undefinedbackground.js:1:1
	<anonymous> moz-extension://e7a53ef5-7f8b-4fb6-847c-b77ee8c87eaa/background.js:1
```

checking
```
cd ~/.thunderbird/csfkj76t.default
grep -rlni e7a53ef5 .
```

appears only in prefs.js
```
("extensions.webextensions.uuids",  ... \"tbsortfolders@xulforum.org\":\"e7a53ef5-7f8b-4fb6-847c-b77ee8c87eaa\ ...
```

**Comment by itagagaki** [comment] 2020-10-03 05:22
Thanks for the checking.
Your and my TB and MSF are exactly the same.
But in your environment, you have got the error "messenger.WindowListener is undefined".
Okay, that certainly doesn't make MSF work..
Can you try the following?

Remove your MSF and install attached version  with "Install Add-on From File..."
(Rename tbsortfolders.xpi.zip to tbsortfolders.xpi before install)
[tbsortfolders.xpi.zip](https://github.com/protz/Manually-Sort-Folders/files/5321127/tbsortfolders.xpi.zip)
And try to do the same.
`▶ Object { manifest: Getter & Setter, ...`
will be displayed on Error Console. Click on this` ▶ `to find out more.
There should be a WindowLister there.
![image](https://user-images.githubusercontent.com/71218184/94984100-81b66100-0583-11eb-8c6b-4cd463dd9540.png)

**Comment by lgbaldoni** [comment] 2020-10-03 09:11
@itagagaki 

> Yes. That's what we call a hamburger menu.
> When you click on it, you will see 'Tools' in the menu that comes up.
> If you click on it further, 'Manually sort folders' should appear. Doesn't it appear?

Oh, I see it now.
Sorry for the false alarm.

**Comment by pgnd** [comment] 2020-10-03 12:55
@itagagaki 

> There should be a WindowLister there.

rm'd MSF
restarted TB
installed the provided xpi
restarted TB
toggled MSF off/on

@ console,

no window listener seen on expension of
```
Object { manifest: Getter & Setter, events: Getter & Setter, types: Getter & Setter, accounts: Getter & Setter, addressBooks: Getter & Setter, contacts: Getter & Setter, mailingLists: Getter & Setter, browserAction: Getter & Setter, cloudFile: Getter & Setter, commands: Getter & Setter, … }
background.js:1:9
```

and  still reports 
```
TypeError: messenger.WindowListener is undefined background.js:2:1
    <anonymous> moz-extension://ef27b5b6-dcbf-4efb-8cda-0a802241b02a/background.js:2
```

**Comment by protz** [comment] 2020-10-03 13:27
Pinging addon hacker extraordinaire @jobisoft ... John, this seems to have shown up during the migration to Thunderbird 78. Do you know any circumstances in which the `windowListener` might be undefined? Everyone seems a little bit puzzled on this bug... thanks very much in advance!

**Comment by itagagaki** [comment] 2020-10-03 13:44
@protz Oh, I just posted it to the [Add-on Developers board](https://thunderbird.topicbox.com/groups/addons/T14b5ce879a33d4dd/is-there-any-way-to-figure-out-why-experimentalapis-is-not-built-in).

**Comment by jobisoft** [comment] 2020-10-03 15:28
@pgnd : Can you try it in a fresh profile? Start thunderbird with the -p option and create a new profile and install the add-on there. Any changes?

Are you using a vanilla Thunderbird? Can your version of Thunderbird been build with the experimental flag set to false?

**Comment by pgnd** [comment] 2020-10-03 15:46
@jobisoft 

already tried with both new profiles, and complete clean installs. same results in all cases -- no trace in menus, and same 'no listener' msg in console.

yep, vanilla TBird. v 68.2.1, atm.  well, as vanilla as the @ Mozilla ftp builds are ....

checking,  all @ about:config "*exper* values are unchanged -- i.e., set to defaults.

**Comment by jobisoft** [comment] 2020-10-03 16:05
68.2.1 ? That is far from being recent. What Distro?

**Comment by pgnd** [comment] 2020-10-03 16:10
sigh.  68.12.1

```
Name 	Thunderbird
Version 	68.12.1
Build ID 	20200929010218
```

**Comment by jobisoft** [comment] 2020-10-03 16:12
Is Quicktext working for you? Using the same API...

**Comment by pgnd** [comment] 2020-10-03 16:16
yep.  when installed/enabled
```
Quicktext	2.15	true	{8845E3B3-E8FB-40E2-95E9-EC40294818C4}
```

works as expected.

**Comment by jobisoft** [comment] 2020-10-03 16:17
Sorry, quicktext for TB68 is not using that API, my bad.

**Comment by jobisoft** [comment] 2020-10-03 16:19
Removedupes for TB68 is using it!
https://addons.thunderbird.net/addon/removedupes

How is that?

**Comment by pgnd** [comment] 2020-10-03 16:29
@jobisoft 

had never used it.

installed
```
Remove Duplicate Messages	0.5	true
```

afaict, no trace of the extension -- or its capabilities -- in Tools/Hamburger/context menus.

**Comment by jobisoft** [comment] 2020-10-03 16:41
Can you install this add-on? It should open an alert box with "hello world" after it has been installed/started.

[experiment.zip](https://github.com/protz/Manually-Sort-Folders/files/5321995/experiment.zip)

You do not need to rename it XPI, you can install the zip file directly.

**Comment by pgnd** [comment] 2020-10-03 16:50
installed
```
Extension containing an experimental API	1	true	experiment@sample.extensions.thunderbird.net
```

restarted TB
no trace of the extension in any menu
no dialog/alert box observed

console on disable/enable reports
```
TypeError: browser.myapi is undefinedbackground.js:1:1
    <anonymous> moz-extension://7639c5ea-0ad3-45d4-a670-788ce7c22dcf/background.js:1
```

**Comment by jobisoft** [comment] 2020-10-03 16:56
Your system has experiments disabled. Get in touch with folks from fedora.

**Comment by pgnd** [comment] 2020-10-03 16:59
What does Fedora have to do with this?  I'm using @ upstream TB, NOT Fedora's TB pkgs.

And devs here asked for my further input ... I'm fine with 2.0.2, which works.

**Comment by jobisoft** [comment] 2020-10-03 17:05
I suggested to get in touch with folks from Fedora, as you are using Fedora. Maybe they know anything about this issue. Fact is, your Thunderbird 68 on your system has Experiments disabled. I have no idea why. If you update to Thunderbird 78 and it still has Experiments disabled (on your system), then you cannot use MSF anymore, as MSF on TB78 only works using Experiments.

Sorry for not being able to help.

**Comment by protz** [comment] 2020-10-03 17:06
Thanks John for the detective work! Much appreciated.

**Comment by protz** [comment] 2020-10-03 17:18
Thinking about it, it could be either:
- that the Fedora-provided Thunderbird was installed at some point and flipped some defaults in user_prefs.js that were retained
- that Fedora packages some global user_prefs.js somewhere (e.g. in /etc) that take precedence over the user's
- that Fedora's Thunderbird and the official Thunderbird are installed concurrently and somewhat the wrong one is launched

**Comment by pgnd** [comment] 2020-10-03 17:22
no to all.

**Comment by protz** [comment] 2020-10-03 17:54
Thanks. I'm afraid at this stage you'll have to investigate, since neither John or I seem to know how it could possibly be the case that experiments are disabled. Technically, this would even qualify as a Thunderbird bug, since Manually Sort Folders is not doing anything wrong.

I have personally confirmed that the test addon John sent works on Thunderbird 68.

The best course of action I can offer is to head over to bugzilla.mozilla.org and try to start a new bug there, along the lines of "experiments API seem to be disabled on Fedora Linux", posting John's test addon there, and stating the error that you obtain from the error console. You could add John and I to the CC field.

Thanks,

Jonathan

**Comment by jobisoft** [comment] 2020-10-03 17:55
My last straw: What happens if you do use the Thunderbird version, which is shipped with Fedora?
