### ISSUE TITLE
 Doesn't work in v58.0b1 

### ISSUE THREAD

**Issue by ghost** [protz/Manually-Sort-Folders#60] opened 2017-12-01 08:30 UTC
Thank you for the very helpfull addon! 

In v58.0b1 Mozilla seems to change something, so that the addon stopped working. 

Best wishes
Christof

**Comment by ckluss** [comment] 2017-12-10 10:50
sadly the links does not work too :( would be cool if the addon persists

https://jonathan.xulforum.org/files/tbsortfolders.xpi

https://www.xulforum.org/go_code

**Comment by RogueScholar** [comment] 2017-12-27 07:19
I'm faced with the same issue. Is the accounts list in the add-on's settings dialog empty for you as well?

**Comment by fra589** [comment] 2018-01-03 09:31
Same issue for me too, account list & folder list stay empty in the setting dialog :-(

**Comment by protz** [comment] 2018-04-09 05:50
Is this still an issue?

**Comment by protz** [comment] 2018-04-09 05:51
Also, where did you find these links from? I changed my website lately and haven't preserved these links

**Comment by fra589** [comment] 2018-04-09 07:13
Hi Jonathan,
I used this link from many-many years... :-) Thanks for this job !
I had not seen the location change...
I think you can close this issue !-)
@++; On the Xul forum or on AMO.

**Comment by MeisterP** [comment] 2018-04-09 07:54
> Same issue for me too, account list & folder list stay empty in the setting dialog :-(

This is still an issue with 60.0b2 (64-bit), tested today

![screenshot from 2018-04-09 09-52-43](https://user-images.githubusercontent.com/781063/38485994-fbb03a36-3bdb-11e8-9b16-c3960e47ccf3.png)

**Comment by fra589** [comment] 2018-04-09 16:42
Oups !
I confirm the bug still an issue on last Thunderbird Windows release (60.0b2 (32 bits)).
This morning, I was under Linux where the extension work well...
@++;

**Comment by Gluups** [comment] 2018-04-09 18:57
Hello,
In case it helps, I confirm that version 1.1.1 of Manually Sort Folders works pretty good on version 52.7.0 of Thunderbird, 32 bits, on Windows 10, 64 bits.
Just one thing, when I click on "refresh the folders list", that goes on top of it, so if I modified something at the bottom I do not see it. Well after that I scroll and it is OK.

**Comment by protz** [comment] 2018-04-10 05:51
Thanks for the feedback. I'll take a look at it.

**Comment by TechSmurf** [comment] 2018-04-26 16:40
Looks like they're doing quite a number to the back end. Link which may save you some footwork: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

**Comment by protz** [comment] 2018-04-30 06:07
Hello,

Here's an update. I just got back from vacation, and took a look at the issues.
- Fixed a bunch of minor cosmetic issues found in the link above.
- Identified some blockers, namely, some ancient, 10+ year old code that I used was recently rewritten, so I need to catch up (the removal of RDF-based XUL trees...). That's likely going to be a few hours of work, which I hope to perform soon.

Any help would be, of course, most appreciated.

**Comment by protz** [comment] 2018-04-30 06:10
I've posted the current status on github and a build is in https://jonathan.protzenko.fr/manually-sort-folders/ -- but it doesn't work as of now.

**Comment by schneeschmelze** [comment] 2018-07-23 12:11
Just to make it clear, as the release of Thunderbird 60 is drawing near, is there any chance for _Manually sort folders_ to be fixed, @protz ? [ATN says](https://addons.thunderbird.net/de/thunderbird/addon/manually-sort-folders/?src=search) it's compatible with TB 45–63. I am quite grateful for your effort and your addon was an important reason for me to switch to Thunderbird, next to Signature Switch. Can I safely upgrade to TB 60 and still trust in _Manually sort folders_?

**Comment by schneeschmelze** [comment] 2018-08-06 22:33
For the record: It does not work on 10.13.6, I'm afraid. :(

**Comment by GH-User** [comment] 2018-08-09 13:12
I can verify that, it doesn't work with TB60.
It seems, @protz is on vacation again. ;)

**Comment by wsmwk** [comment] 2018-09-27 23:53
Further discussion in https://github.com/protz/Manually-Sort-Folders/issues/64 which is a duplicate?

**Comment by x-ji** [comment] 2018-10-30 14:56
Duplicate of #67? The version by @Ximi1970 at https://github.com/Ximi1970/Manually-Sort-Folders/releases seems to work.

**Comment by rsleventhal** [comment] 2018-11-15 15:36
I can confirm that this issue persists in 60.2.1 (64-bit) on Linux (Xubuntu 18.04)

**Comment by marcolopes** [comment] 2018-11-27 02:55
Stopped working on TB 60.3.1 (i updated from 5x.x.x) on WINDOWS 10.

**Comment by Gluups** [comment] 2018-11-27 20:02
> 
> 
> Stopped working on TB 60.3.1 (i updated from 5x.x.x) on WINDOWS 10.

Would you mind giving some more details ?
What happened, the lists of accounts and folders were no more fulfilled ?
Or something else ?

**Comment by rsleventhal** [comment] 2018-11-27 20:17
On my 60.2.1(64 bit) Linux installation, the folders and/or accounts are not populated in the plugin window.

**Comment by Gluups** [comment] 2018-11-27 20:23
> On my 60.2.1(64 bit) Linux installation, the folders and/or accounts are not populated in the plugin window.

Were they beforehand ?
It is important to know whether you never obtained a correct function, or whether you obtained one at some time, that for an unknown reason ceased functioning.
And the most details you can give about what changed on your machine, the best it is.

**Comment by x-ji** [comment] 2018-11-27 22:43
Stating the obvious is whether you tried out the fix at https://github.com/Ximi1970/Manually-Sort-Folders/releases, which still has some quirks but should work.

**Comment by marcolopes** [comment] 2018-11-28 03:55
> > Stopped working on TB 60.3.1 (i updated from 5x.x.x) on WINDOWS 10.
> 
> Would you mind giving some more details ?
> What happened, the lists of accounts and folders were no more fulfilled ?
> Or something else ?
> Did you have a correct function on these versions beforehand ?
> Did you change anything or did anything change in your context ?
> 
> By the way, as far as I am well informed the last recent version is 1.2.0pre3, but somebody obtained good results with 1.2.0pre2 and not with pre3, so please do some tests with pre2 and pre1.

I'm using version 1.1.1. Screen attached.

Folders maintain the last defined order, but i can't change anything (combo boxes are empty)
![screenshot 2018-11-28 03 51 58](https://user-images.githubusercontent.com/431889/49127986-67453980-f2c1-11e8-9ad1-13021d539ffd.png)

**Comment by schneeschmelze** [comment] 2018-11-28 09:12
For the record: 1.2.0pre3 works on TB 60.3.1 on macOS 10.13.6.

**Comment by rsleventhal** [comment] 2018-11-28 12:58
I concur with schneeschmelze.  1.2.0pre3 works on TB 60.2.1 on Xubuntu 18.04.1

**Comment by Gluups** [comment] 2018-11-28 19:33
> I'm using version 1.1.1. Screen attached.

Version 1.1.1 is obsolete for a long time.
Try some from there :
[https://github.com/Ximi1970/Manually-Sort-Folders/releases](url)

**Comment by protz** [comment] 2018-12-16 04:48
My sincerest apologies for the long delay with this update. Various life things got in the way, not to mention my research work which is my main focus of interest these days. I am happy to announce that, in spite of it all, this addon which I created while an undergrad nearly 10 years ago just received an update that makes it compatible with Thunderbird 60! Thunderbird should update automatically in a few days, as soon as the new version is accepted. If you'd rather upgrade now:
- download the version "1.2.0pre3" listed in the comments above, or from my website: https://jonathan.protzenko.fr/manually-sort-folders/manually-sort-folders-201812152042.xpi
- then, in Tools > Addons, hit the cog, the do "install addon from file".

Thanks again to @Ximi1970 for the update.

Hope this helps!

Best,

Jonathan

**Closed by protz** 2018-12-16 04:48 UTC
