### ISSUE TITLE
Need to implement support for the new addons menu

### ISSUE THREAD

**Issue by kossahl** [protz/Manually-Sort-Folders#108] opened 2019-12-20 09:04 UTC
With 68.3 Mozilla finally made the 68 updates available via the updater for the 60 version. So my Thunderbird updated. I was also happy to see an update for manually sort folder and updated right away.
Sadly it does not work at all. No Options for the Plugin can be found, nor did it use the old options (which should be present).

**Comment by Tormentor667** [comment] 2019-12-20 17:25
I can confirm, it does not work.

**Comment by nicochto** [comment] 2019-12-20 21:02
> No Options for the Plugin can be found

In my case the plug-in options are not available in the Tools submenu from the "Thunderbird menu" in the top right corner:

![1 - Tools submenu from the menu button in the top right corner](https://user-images.githubusercontent.com/48647592/71292554-548e1e80-2374-11ea-9a23-1e1a01c86ee9.png)

…but they are available in the Tools menu from the old-fashioned menu bar at the top (hidden by default, press [Alt] to show it):

![2 - Tools menu from the top menu bar](https://user-images.githubusercontent.com/48647592/71292631-5952d280-2374-11ea-93cf-3f7809c03bed.png)

**Comment by kossahl** [comment] 2019-12-20 22:32
@nicochto for me there is no tools menu in thunderbird 68.3.1
Can you confirm you use the same version on Windows 10 x64?

**Comment by nicochto** [comment] 2019-12-20 23:21
@kossahl No, I use Windows 7 x64. It seems to be a different issue.

**Comment by erwanlescop** [comment] 2019-12-24 08:08
It does not work, and the trick mentioned does not work either for me.

**Comment by toolstack** [comment] 2019-12-24 13:57
I can confirm the same behaviour on TB 68.2.2, 64bit, Ubuntu 19.10.

The "alt" trick doesn't work on Linux, but F10 does bring up the old menu and you can then access the addon settings.

**Comment by jdtrower** [comment] 2019-12-28 00:56
I can confirm that the "alt" trick will allow you to access the addon settings on TB 68.3.1 on Windows 10.0.17134 Build 17134 x64.  However, even though I can get the addon settings to load, I can't set the Local Folders to be located at the top even though I have it set as the default account in the addon settings. I have changed the default account to "First RSS or Mail account in the list" then restarted TB.  I would then change the default account back to "Local Folders" and yet Local Folder remains below all of the individual accounts but above the RSS Feeds.  Prior to the recent TB update, this setting worked fine and allowed me to have the Local Folders above all the individual accounts.

**Comment by MysticJay** [comment] 2019-12-29 23:18
W10. 1809 (German)
TB 68.3.1 (32-Bit) (German)
Addon visible in menu, no tricks needed.
"Local Folder" (also not after renaming to "Lokaler Ordner") is default but does not move to TOP position.

**Comment by guy-teube** [comment] 2020-01-07 14:55
Same here with TB 68.2.2 (64 bits), on Ubuntu 18.04 64 bits. The extension is active but not usable.
Alt touch doen't not make appear the alternative/old menu.

**Comment by pwnoobz** [comment] 2020-01-07 19:22
W7 TB 68.3 same thing happens. I have nothing in my tools menu.

**Comment by protz** [comment] 2020-07-06 16:27
Duplicate of #117

**Closed** 2020-07-06 16:27 UTC
Labels: bug
