### ISSUE TITLE
Local folders cannot be moved to top after upgrade to TB68.3.1 and upgrade the add on

### ISSUE THREAD

**Issue by hdoothr** [protz/Manually-Sort-Folders#110] opened 2020-01-09 11:50 UTC
Before TB 68.3.1 I was able to locate the local folders at the top of my list. After upgrading it is not possible any more.

**Comment by protz** [comment] 2020-01-13 13:13
duplicate of #101

**Closed** 2020-01-13 13:13 UTC
